# **A Series of Numpy Problems**

In [43]:
# Libraries
import numpy as np

In [ ]:
# Print out the Numpy Version & Buid Info
print(f"NumPy Version Number: {np.__version__}\n Numpy Build Info: {np.show_config()}")

In [7]:
# Test Data
A = np.array([1,2,3])
print("Original Array: ")
print(A)

# Test Whether the Array Contains Zeros
print("Test if None of the Elements are Zero:")
print(np.all(A))

Original Array: 
[1 2 3]
Test if None of the Elements are Zero:
True


In [18]:
# Empty Array
A = np.empty((3,4))
print(f"Matrix A: \n {A}")

# Full Array
B = np.full((3,3),2)
print(f"Matrix B: \n {B}")

# Array of Zeros
C = np.zeros((2,3))
print(f"Matrix C: \n {C}")

Matrix A: 
 [[3.77914480e-315 0.00000000e+000 1.01855798e-312 9.54898106e-313]
 [1.03977794e-312 1.01855798e-312 1.23075756e-312 1.20953760e-312]
 [1.06099790e-312 9.76118064e-313 1.18831764e-312 1.90979621e-312]]
Matrix B: 
 [[2 2 2]
 [2 2 2]
 [2 2 2]]
Matrix C: 
 [[0. 0. 0.]
 [0. 0. 0.]]


In [25]:
# Look for a Specific Row inside an Array
A = np.full((3,3),2)
print([1,2,4] in A.tolist())
print([2,2,2] in A.tolist())

# Count A Specific Row inside an Array
count = repr(A).count("2, 2, 2")
print(f"Number of Sequences: {count}")

False
True
Number of Sequences: 3


In [31]:
# Preparing a Matrix
B = np.matrix('[1,2,3; 4,7,2; 8,5,6]')

# Get Number of Rows & Columns
print(f"Shape of B: {B.shape}")

# Find the Maximum Number
print(f"Maximum Value: {B.max()}")

# Find the Minimum Number
print(f"Minimum Value: {B.min()}")

Shape of B: (3, 3)
Maximum Value: 8
Minimum Value: 1


In [33]:
# Finding the Sum of the Entire Matrix
print(f"Sum of Values: {B.sum()}")

# Find Sum of Diagonal
diagonal = B.diagonal()
print(f"Sum of Diagonal: {np.sum(diagonal)}")

# Find Trace = Sum
print(f"Trace of Matrix: {np.trace(B)}")

Sum of Values: 38
Sum of Diagonal: 14
Trace of Matrix: 14


In [51]:
# ISML Matrix Referesher
C = np.matrix('[6,1,1; 4,-2,5; 2,8,7]')

# Matrix Multiplication
print(f"Matrix Multiplication of B & C: \n {np.matmul(B, C)}\n")
print(f"Matrix Multiplication of B & C: \n {B@C}\n")
print(f"Matrix Multiplication of B & C: \n {np.dot(B, C)}\n")

# Finding the EigenValues & EigenVectors of a Matrix
eigenvalues, eigenvectors = np.linalg.eig(C)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Matrix Multiplication of B & C: 
 [[20 21 32]
 [56  6 53]
 [80 46 75]]

Matrix Multiplication of B & C: 
 [[20 21 32]
 [56  6 53]
 [80 46 75]]

Matrix Multiplication of B & C: 
 [[20 21 32]
 [56  6 53]
 [80 46 75]]

Eigenvalues: [11.24862343  5.09285054 -5.34147398]
Eigenvectors:
 [[ 0.24511338  0.75669314  0.02645665]
 [ 0.40622202 -0.03352363 -0.84078293]
 [ 0.88028581 -0.65291014  0.54072554]]


In [52]:
# Finding the Determinant of a Matrix
print(f"Determinant of C:{np.linalg.det(C)}")

# How to Find the Inverse of a Matrix
print(f"Inverse of C:\n {np.linalg.inv(C)}")


Determinant of C:-306.0
Inverse of C:
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]
